- type: job
  id: PirateFirstMate
  name: job-name-pirate-first-mate
  description: job-description-pirate-first-mate
  playTimeTracker: JobPirateFirstMate
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 # 6 hours # mono
    - !type:RoleTimeRequirement # mono
      role: JobPirate # mono
      time: 10800 # 3 hours
  #whitelisted: true # mono - comment out
  startingGear: PirateFirstMateNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirateFirstMate"
  supervisors: job-supervisors-captain
  weight: 30
  displayWeight: 30
  setPreference: true
  access:
  - Pirate
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - PirateNF
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PirateFirstMateNFGear
  equipment:
    ears: ClothingHeadsetAltFreelancer
    #belt: ClothingBeltUtility # mono
    pocket1: BasePirateUplinkPirateCrew
    pocket2: AppraisalTool
  storage: # mono
    back:
    - RadioHandheldNF
