#DISCLAIMER: THIS FILE IS LABELED "WHITELISTED" AS THEY WERE ALL WHITELISTED ROLES ON FRONTIER, HOWEVER I WILL BE REMOVING THEIR WHITELISTS WHILE PRESERVING THIS FILE TO KEEP THEIR PROTOTYPES.

- type: ghostRole
  id: BabyDragon
  name: ghost-role-information-baby-dragon-name
  description: ghost-role-information-baby-dragon-description
  rules: ghost-role-information-emotional-support-rules
  entityPrototype: DragonEgg # Unsure if this should be MobDragonPet (the actual dragon) - no ghost role component

# Pets
- type: ghostRole
  id: EmotionalSupportPet
  name: ghost-role-information-emotional-support-name
  description: ghost-role-information-emotional-support-description
  rules: ghost-role-information-emotional-support-rules
  entityPrototype: MobCatGhost # TODO: replace this with a random emotional support pet entity

# Others
- type: ghostRole
  id: CatCappy
  name: ghost-role-information-cappy-name
  description: ghost-role-information-cappy-description
  rules: ghost-role-information-emotional-support-rules
  entityPrototype: MobCatCappy

- type: ghostRole
  id: CatClarpy
  name: ghost-role-information-clarpy-name
  description: ghost-role-information-clarpy-description
  rules:  ghost-role-information-emotional-support-rules
  entityPrototype: MobCatClarpy

- type: ghostRole
  id: CatClippy
  name: ghost-role-information-clippy-name
  description: ghost-role-information-clippy-description
  rules: ghost-role-information-emotional-support-rules
  entityPrototype: MobCatClippy

- type: ghostRole
  id: CatMistake
  name: ghost-role-information-mistake-name
  description: ghost-role-information-mistake-description
  rules: ghost-role-information-emotional-support-rules
  entityPrototype: MobCatMistake

- type: ghostRole
  id: CatBloodCult
  name: ghost-role-information-cult-cat-name
  description: ghost-role-information-cult-cat-description
  rules:  ghost-role-information-emotional-support-rules
  entityPrototype: MobCatBloodCult

- type: ghostRole
  id: MonkeyPunpun
  name: ghost-role-information-punpun-name
  description: ghost-role-information-punpun-description
  rules: ghost-role-information-nonantagonist-rules
  entityPrototype: MobMonkeyPunpun

- type: ghostRole
  id: SentientArtifact
  name: ghost-role-information-artifact-name
  description: ghost-role-information-artifact-description
  rules: ghost-role-information-freeagent-rules
  entityPrototype: VariedXenoArtifactItem # Don't spawn this.  FIXME: entity has no ghost role component.

- type: ghostRole
  id: KoboldYipyip
  name: ghost-role-information-yipyip-name
  description: ghost-role-information-yipyip-description
  rules: ghost-role-information-nonantagonist-rules
  entityPrototype: MobKoboldYipyip

- type: ghostRole
  id: NFBuddy
  name: nf-ghost-role-information-buddy-name
  description: nf-ghost-role-information-buddy-description
  rules: ghost-role-information-nonantagonist-rules
  entityPrototype: NFMobHumanBuddy
