# SPDX-FileCopyrightText: 2025 HungryCuban
# SPDX-FileCopyrightText: 2025 Redrover1760
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: accessLevel
  id: USSP
  name: id-card-access-level-ussp

- type: accessLevel
  id: USSPHigh
  name: id-card-access-level-ussp-high

- type: accessLevel
  id: USSPCommand
  name: id-card-access-level-ussp-command

- type: accessGroup
  id: USSPAA
  tags:
  - USSP
  - USSPHigh
  - USSPCommand
  - Mercenary
  - Cryogenics
  # SHIPS BECAUSE VOUCHER SHITCODE - DO NOT USE THESE FOR **ANYTHING**!!!
  - USSPGadyuka
  - USSPTunguska
  - USSPDrakon
  - USSPNatisk
  - USSPSekunda
  - USSPGruznyk

- type: accessGroup
  id: USSPHigh
  tags:
  - USSP
  - USSPHigh
  - Mercenary
  # SHIPS BECAUSE VOUCHER SHITCODE - DO NOT USE THESE FOR **ANYTHING**!!!
  - USSPGadyuka
  - USSPTunguska
  - USSPDrakon
  - USSPNatisk
  - USSPSekunda
  - USSPGruznyk

- type: accessGroup
  id: USSPLow
  tags:
  - USSP
  - Mercenary
  # SHIPS BECAUSE VOUCHER SHITCODE - DO NOT USE THESE FOR **ANYTHING**!!!
  - USSPGadyuka
  - USSPTunguska
  - USSPDrakon
  - USSPNatisk
  - USSPSekunda
  - USSPGruznyk
