- type: job
  id: Pilot
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: JobPilot
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600 # mono - change to 1hr
  startingGear: PilotGear
  icon: "JobIconPilot"
  supervisors: job-supervisors-hire
  weight: 2 # Prioritize station & department jobs
  displayWeight: 30 # Second from the top
  accessGroups: # Frontier
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PilotGear
