# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 LordEclipse
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Cheackraze
# SPDX-FileCopyrightText: 2023 Kesiath
# SPDX-FileCopyrightText: 2023 LankLTE
# SPDX-FileCopyrightText: 2023 MagnusCrowe
# SPDX-FileCopyrightText: 2023 Nairod
# SPDX-FileCopyrightText: 2023 Nemanja
# SPDX-FileCopyrightText: 2023 Puro
# SPDX-FileCopyrightText: 2023 SpaceCat
# SPDX-FileCopyrightText: 2023 Vasilis The Pikachu
# SPDX-FileCopyrightText: 2023 brainfood1183
# SPDX-FileCopyrightText: 2023 lzk
# SPDX-FileCopyrightText: 2023 lzk228
# SPDX-FileCopyrightText: 2024 Checkraze
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 Ed
# SPDX-FileCopyrightText: 2024 Kot
# SPDX-FileCopyrightText: 2024 Maxtone
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 Salvantrix
# SPDX-FileCopyrightText: 2024 SlamBamActionman
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2024 Winkarst
# SPDX-FileCopyrightText: 2024 deltanedas
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2025 Blu
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  weight: -90
  primary: false
  editorHidden: true # Frontier

- type: department
  id: Civilian
  name: department-Civilian
  description: department-NFCivilian-description # Frontier
  color: "#9FED58"
  weight: -10
  roles:
  # - Bartender # Frontier
  # - Botanist # Frontier
  # - Boxer # Frontier
  # - Chaplain # Frontier
  # - Chef # Frontier
  # - Clown # Frontier
  # - HeadOfPersonnel # Frontier
  # - Lawyer # Frontier
  # - Librarian # Frontier
  # - Mime # Frontier
  # - Musician # Frontier
  # - Passenger # Frontier
  # - Reporter # Frontier
  # - Visitor # Frontier
  # - Zookeeper # Frontier
  # - ServiceWorker # Frontier
  - Contractor # Frontier
  - Mercenary # Frontier
  - Pilot # Frontier
  - Borg # Frontier

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-NFCentralCommand-description # Frontier
  color: "#0c344d"
  roles:
  - CentralCommandOfficial
#  - CBURN # Frontier
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
#  - DeathSquad # Frontier
  - ERTMailCarrier # Frontier
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-NFCommand-description # Frontier
  color: "#334E6D"
  roles:
  # - Captain # Frontier
  # - ChiefEngineer # Frontier
  # - ChiefMedicalOfficer # Frontier
  # - HeadOfPersonnel # Frontier
  # - HeadOfSecurity # Frontier
  # - ResearchDirector # Frontier
  # - Quartermaster # Frontier
  # - CentralCommandOfficial # Frontier
  # - CBURN # Frontier
  # - ERTLeader # Frontier
  # - ERTChaplain # Frontier
  # - ERTJanitor # Frontier
  # - ERTMedical # Frontier
  # - ERTSecurity # Frontier
  # - ERTEngineer # Frontier
  # - DeathSquad # Frontier
  - StationRepresentative # Frontier
  - Sheriff  # Frontier
  - StationTrafficController # Frontier
  - DirectorOfCare # Mono
  primary: false
  weight: 100

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  weight: -94
  primary: false
  editorHidden: true # Frontier

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  weight: 0
  roles: # Mono
  - DirectorOfCare # Mono
  - MdMedic # Mono

- type: department
  id: Security
  name: department-Security
  description: department-NFSecurity-description # Frontier
  color: "#326DA8" # Mono
  weight: 1 # Frontier: 20<1 - accounted for in jobs
  roles:
#  - Detective # Frontier
#  - HeadOfSecurity # Frontier
#  - SecurityCadet # Frontier
#  - SecurityOfficer # Frontier
#  - Warden # Frontier
  - PrisonGuard ##nyano
  - Brigmedic # Frontier
#  - SecurityGuard # Frontier
  - NFDetective # Frontier
  - Cadet # Frontier
  - Deputy # Frontier
  - Bailiff # Frontier
  - Sheriff # Frontier
  - SeniorOfficer # Frontier
  - PublicAffairsLiaison # Frontier
  - TsfEngineer # Mono

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#D381C9"
  weight: -92
  primary: false
  editorHidden: true # Frontier

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi
  editorHidden: true # Frontier
  primary: false # Frontier

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: -91
  primary: false
  editorHidden: true # Frontier
