# SPDX-FileCopyrightText: 2020 20kdc
# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-FileCopyrightText: 2020 FL-OZ
# SPDX-FileCopyrightText: 2020 Hugo Laloge
# SPDX-FileCopyrightText: 2020 VÃ­ctor Aguilera Puerto
# SPDX-FileCopyrightText: 2020 ike709
# SPDX-FileCopyrightText: 2021 Moony
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Leon Friedrich
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Peptide90
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Cheackraze
# SPDX-FileCopyrightText: 2023 Checkraze
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2023 Kesiath
# SPDX-FileCopyrightText: 2023 Kevin Zheng
# SPDX-FileCopyrightText: 2023 Nemanja
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 coolmankid12345
# SPDX-FileCopyrightText: 2023 freeman2651
# SPDX-FileCopyrightText: 2023 ninruB
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 ErhardSteinhauer
# SPDX-FileCopyrightText: 2024 Salvantrix
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2025 Daniel Lenrd
# SPDX-FileCopyrightText: 2025 core-mene
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: SecurityGuard
  name: job-name-security-guard
  description: job-description-security-guard
  playTimeTracker: JobSecurityGuard
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # Frontier - 10 hrs
  startingGear: SecurityGuardGear
  alwaysUseSpawner: true
  icon: "JobIconSecurityGuard"
  supervisors: job-supervisors-sr
  weight: 80
  displayWeight: 20 # Second from the bottom
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Mercenary
  - Captain
  - Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SecurityGuardGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses #ClothingEyesGlassesSecurity
  storage:
    back:
    - EncryptionKeyService
    - EncryptionKeySecurity
    - Flash
    - ShipVoucherFrontierGuard
