- type: job
  id: USSPRifleman
  name: job-name-ussp-rifleman
  description: job-description-ussp-rifleman
  playTimeTracker: JobUSSPRifleman
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 14400 # 4 hrs
  startingGear: USSPRiflemanGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconSecurityCadet" # TODO - new USSP icons
  supervisors: job-supervisors-ussp-sergeant
  canBeAntag: false
  weight: 10
  displayWeight: 10
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, UsspTrackingImplant ]
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - USSP
  accessGroups:
  - GeneralAccess
  - USSPLow

- type: startingGear
  id: USSPRiflemanGear
  equipment:
    pocket1: WeaponPistolPollock
    pocket2: MagazinePistol
  storage:
    back:
    - WeaponRifleAK502
