# SPDX-FileCopyrightText: 2023 Cheackraze
# SPDX-FileCopyrightText: 2023 Kesiath
# SPDX-FileCopyrightText: 2023 Nemanja
# SPDX-FileCopyrightText: 2023 Puro
# SPDX-FileCopyrightText: 2024 AndresE55
# SPDX-FileCopyrightText: 2024 Checkraze
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 ErhardSteinhauer
# SPDX-FileCopyrightText: 2024 Salvantrix
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2025 EctoplasmIsGood
# SPDX-FileCopyrightText: 2025 Maxtone
# SPDX-FileCopyrightText: 2025 Redrover1760
# SPDX-FileCopyrightText: 2025 Your Name
# SPDX-FileCopyrightText: 2025 core-mene
# SPDX-FileCopyrightText: 2025 mikusssssss
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic-nf
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # 12 hours # mono
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hours # mono
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 64800 # 18 hours # mono
  startingGear: BrigmedicGear
  icon: JobIconBrigmedicNF
  supervisors: job-supervisors-bailiff
  weight: 125
  displayWeight: 35
  canBeAntag: false
  accessGroups:
  - GeneralNfsdBrigmedicAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
    - type: SurgerySpeedModifier
      SpeedModifier: 1.65
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: BrigmedicGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
    - EncryptionKeyMedical
    - Magazine45_ACPPistolFMJ
    - BaseSecurityUplinkRadioOfficer #Mono: Changed to officer uplink
    - RadioHandheldNF # Mono
