- type: job
  id: Deputy
  name: job-name-deputy
  description: job-description-deputy
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # 12 hours # mono
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hours # mono
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 64800 # 18 hours # mono
  startingGear: DeputyGear
  icon: JobIconDeputy
  supervisors: job-supervisors-sergeant
  weight: 130
  displayWeight: 40
  canBeAntag: false
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: DeputyGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
    - MagazinePistol
    - BaseSecurityUplinkRadioDeputy #Mono: Added Deputy uplink
    - RadioHandheldNF # Mono
