- type: job
  id: NFDetective
  name: job-name-nf-detective
  description: job-description-nf-detective
  playTimeTracker: JobDetective
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800 # 3 hours # mono
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hours # mono
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 18000 # 5 hours # mono
  startingGear: NFDetectiveGear
  icon: JobIconNFDetective
  supervisors: job-supervisors-bailiff
  weight: 110
  displayWeight: 20
  canBeAntag: false
  setPreference: false # mono
  access:
  - Detective
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: NFDetectiveGear
  equipment:
    pocket1: WeaponRevolverInspector
    pocket2: FlashlightNfsdLite
  storage:
    back:
    - Flash
    - SpeedLoaderMagnum
    - SpeedLoaderMagnumRubber
    - ForensicPad
    - ForensicScanner
    - FederationMilitaryCredit10
    - LogProbeCartridge
    - RubberStampDetective
    - ContrabandForensicsModule
